### ISSUE TITLE
Remove unused websocket-based webhooks

### ISSUE THREAD

**Issue by aruiz14** [rancher/gitjob#339]
This functionality was meant to be used to expose `gitjob` from Rancher via `steve`'s aggregation websockets. However, a typo prevented this from working for a long time.
Up to this point, there were no reports of this functionality not working, and we have documentation on how to expose GitJob webhooks via Ingress, so it's better to remove this unnecessary complexity from the code.

**Comment by manno** [comment]
Removing it now, since it blocks our upgrade to wrangler/v2.

https://github.com/rancher/rancher/issues/42861#issuecomment-1768445968
