### ISSUE TITLE
Add Metrics

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/gitjob#46]
Hello, it would be helpful to collect metrics from a GitJob. While working on https://github.com/rancher/fleet/pull/694 I noticed there are no metrics for GitJobs as it comes from this repo which also exposes no Metrics.

It would be good to keep count on things like total polls, and polls per repo, etc.

**Comment by manno** [comment]
Possible follow-up to https://github.com/rancher/fleet/issues/1408

**Comment by manno** [comment]
Closing in favor of https://github.com/rancher/fleet/issues/1408
