### ISSUE TITLE
Add CI testing to Gitjob

### ISSUE THREAD

**Issue by mattfarina** [rancher/gitjob#67]
Add automated CI testing.

There are currently minimal tests (only one package has them and it's less than 4% coverage). But, we should run tests and add tests. At the least, it will make sure the code builds.

**Comment by manno** [comment]
- [ ] ~~add tests for the other examples (they require much more setup)~~
- [ ] ~~port tests from fleet here (might be faster, but would reduce coverage of fleet's setup)~~
- [x] add test for ssh (seems necessary to catch that early) https://github.com/rancher/gitjob/pull/83
- [x] fix helm package script while at it (helm chart release is unusable without deleting the crd folder) https://github.com/rancher/gitjob/pull/80

Missing / postponed:
- [ ] test for webhook, termination examples 
- [ ] behavior might be better tested by integration tests (external git repo control and setup is too much infrastructure) 
  - [ ] crd spec fields (by commit)
  - [ ] triggers, enqueues, ..
